### ISSUE TITLE
[Crash]: java.lang.AbstractMethodError: Receiver class fuzs.thinair.ThinAir$$Lambda$13944/0x0000000801e2f5c8 does not define or inherit an implementation of the resolved method 'abstract void onChunkLoad(net.minecraft.class_3218, net.minecraft.class_2818)' of interface fuzs.puzzleslib.api.event.v1.level.ServerChunkEvents$Load.

### ISSUE THREAD

**Issue by Feliks-WR** [Fuzss/thinair#13] opened 2023-11-04 10:27 UTC
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

Open mod with my other mods (https://modrinth.com/modpack/better-experiences).

### Crash Report (Required)

https://gist.github.com/Feliks-WR/3922ec0d66947129bf35f7fef899e798

### latest.log (Optional)

https://mclo.gs/MHeYQtc

**Comment by RedstoneWizard08** [comment] 2023-11-05 14:47
I also just had this error
https://gist.github.com/RedstoneWizard08/1b2558113da636c45ee1c89348dc61d9

**Comment by Fuzss** [comment] 2023-11-05 21:51
Caused by an update to Puzzles Lib. Fixed in Thin Air v8.1.0.

**Closed by Fuzss** 2023-11-05 21:51 UTC
Labels: bug
